source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', path: '../rails-1/'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem "sidekiq"

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# gem 'capistrano', '~> 3.0.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
# gem 'glacial_sierra_9138', path: '/home/vikas/rails_app/railsgenerator/../gems/glacial_sierra_9138'

# gem 'glacial_sierra_4949', path: '/home/vikas/rails_app/railsgenerator/../gems/glacial_sierra_4949'

# gem 'glacial_sierra_1337', path: '/home/vikas/rails_app/railsgenerator/../gems/glacial_sierra_1337'

gem 'stonehenge_5145', path: '/home/vikas/rails_app/railsgenerator/../gems/stonehenge_5145'

gem 'wall_plant_6020', path: '/home/vikas/rails_app/railsgenerator/../gems/wall_plant_6020'

gem 'disturbed_equilibrium_1772', path: '/home/vikas/rails_app/railsgenerator/../gems/disturbed_equilibrium_1772'

gem 'bad_leopard_9333', path: '/home/vikas/rails_app/railsgenerator/../gems/bad_leopard_9333'
